  services:
    db:
      image: postgres:13-bookworm
      environment:
        POSTGRES_PASSWORD: workout
        POSTGRES_USER: workout
        POSTGRES_DB: workout
      ports:
        - 5432:5432